
build_from:
  aarch64: ghcr.io/abriotde/openhems-sample:main
  amd64: ghcr.io/abriotde/openhems-sample:main
  armv7: ghcr.io/abriotde/openhems-sample:main
codenotary:
  base_image: contact@openhomesystem.com
  signer: contact@openhomesystem.com
